= Docker og Kubernetes
Espen Strømland <espen.stromland@skatteetaten.no> & Bjarte Karlsen <bjarte.karlsen@skatteetaten.no>
2020-09-10
:revnumber: {project-version}

== Hvem er vi?
- Bjarte Stien Karlsen
  * Ferdig utdannet 2005, startet i Skatteetaten våren 2015.
  * Arkitekt og utvikler.
- Espen Strømland
  * Ferdig utdannet 2015, startet i Skatteetaten våren 2016 
  * Teamleder og utvikler.

- Alle i vårt team har gått på UiA Grimstad / Kristiansand.


== Litt om Skatteetaten
- 500+ utviklere, ca 6700 totalt.
- Startet med OpenShift i 2015.
- Våre oppgaver i Skatt:
  * Utvikle verktøy som forenkler bruk av container platform. 
  * Automatisere og standardisere bygg og leveransekjeden.
  * Utviklingsstøtte.

include::docker.adoc[]
include::kubernetes.adoc[]

== Container
- Begreper
  - Dockerfile
  - Image
  - Tag
  - Container
  - Repository
- Prinsipper
- Lagdelt
- Minste privilegier
- Self contained
- Deler kjerne (Vis bilde)
- Immutable
- Docker mest brukte kontainerteknologi

== Container demo
Containere demo	15 min	
Tag
Local caching
Start image
Vise noen kjekke docker kommandoer

Forenklet bruk av kontainere	5 min	
Nevne andre teknologier som gjør det enklere å jobbe med kontainere.
https://buildpacks.io/
https://www.baeldung.com/spring-boot-docker-images

Buildpacks demo	5 min	Vise bruk av buildpacks	
Pause	10 min	Kan stille spørsmål i pausen	
Dele image / containere med andre	5 min	
DockerHub = Container Registry

DockerHub demo	5 min	
Publiser image til DockerHub
Start Image fra DockerHub


Hvordan gjør vi det i Skatteetaten?	10 min	
500+ utviklere
Behov for automatisering og standardisering
Kontrakter - Enklere konsepter
GitHub - https://github.com/Skatteetaten

Pause	10 min	Kan stille spørsmål i pausen	
Hands on	? min	Studentene prøver selv?

