@startuml
scale 600 height
!include skatt.iuml


Deployment<<OS1>> -->[ruller ut ny versjon]ReplicaSet <<OS1>>
ReplicaSet -->[starter] Pod <<OS3>>

Pod -left->[inneholder]Container <<OS2>>
Service <<OS1>>-left->[lastbalanserer] Pod
Ingress <<OS1>> -up->[eksponerer] Service
Pod --> [bruker]ConfigMap<<OS1>>
Pod --> [bruker]Volume<<OS1>>
Pod --> [bruker]Secret<<OS1>>
@enduml