apiVersion: v1
kind: Service
metadata:
    labels:
        app: uia-app
    name: uia-app
spec:
    ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app: uia-app
    type: LoadBalancer