apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: uia-app
    name: uia-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: uia-app
    template:
        metadata:
            labels:
                app: uia-app
        spec:
            containers:
                - image: stromland/uia-app:1
                  imagePullPolicy: Always
                  name: uia-app
                  ports:
                      -   containerPort: 8080
                  env:
                     - name: NAME
                       valueFrom:
                         fieldRef:
                           fieldPath: metadata.name
                  readinessProbe:
                      tcpSocket:
                          port: 8080