apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: greeter
    name: greeter
spec:
    replicas: 2
    selector:
        matchLabels:
            app: greeter
    template:
        metadata:
            labels:
                app: greeter
        spec:
            containers:
                - image: stromland/greeter:1
                  imagePullPolicy: Always
                  name: greeter
                  ports:
                      -   containerPort: 8080
                  env:
                     - name: NAME
                       valueFrom:
                         fieldRef:
                           fieldPath: metadata.name
                  readinessProbe:
                      tcpSocket:
                          port: 8080