apiVersion: v1
kind: Pod
metadata:
    name: greeter
    labels:
        app: greeter
spec:
    containers:
        -   image: stromland/greeter:1
            name: greeter
            ports:
                -   containerPort: 8080