apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: repeater
    name: repeater
spec:
    replicas: 2
    selector:
        matchLabels:
            app: repeater
    template:
        metadata:
            labels:
                app: repeater
        spec:
            containers:
                - image: stromland/repeater:1
                  imagePullPolicy: Always
                  name: repeater
                  env:
                      - name: GREETER_SERVICE_URL
                        value: "http://greeter:8080"